#!/usr/bin/env bash

branches=""
for dir in $1/*; do
    if [[ -d ${dir} ]]; then
        pushd ${dir} > /dev/null
        branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
        if
            [[ "${branch}" != "master" &&
               ! "${branch}" =~ "(no branch)" &&
               ! "${branch}" =~ ^\((HEAD )?detached ]]
        then
            branches="${branches}\n${dir} ${branch}"
        fi
        popd > /dev/null
    else
        echo "No such directory"
    fi
done
echo -e ${branches} | column -t -s ' '
