#!/bin/bash
export XAUTHORITY=/home/tjarvstrand/.Xauthority
export DISPLAY=:0
BUSSES=( $(get-edid 2>&1 | grep "potential busses found:" | cut -d ':' -f 2) )
#test with nohup
nohup su tjarvstrand -l -c "scr auto ${#BUSSES[@]} /home/tjarvstrand/udev.log" &>> /home/tjarvstrand/udev.log
