#!/usr/bin/env bash

unset SSH_ASKPASS
unset GIT_ASKPASS

ARG=${1}

function log {
    if [[ "${ARG}" != "-q" ]]
    then
        echo ${@}
    fi
}

function start_ssh_agent {
    log "Initialising new SSH agent..."
    /usr/bin/ssh-agent | grep -v '^echo' > "${SSH_ENV}"
    log succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
}

function ensure_ssh_agent_started {
    if [ -f "${SSH_ENV}" ]; then
        . "${SSH_ENV}" > /dev/null
        ps -eo pid | grep ${SSH_AGENT_PID} > /dev/null && return
        rm -f "${SSH_ENV}"
    fi
    start_ssh_agent;
}

function ensure_ssh_key_added {
    if ssh-add -l | cut -d ' ' -f 3 | grep ${HOME}/.ssh/id_rsa > /dev/null
    then
        log id_rsa already added to agent
    else
        log $(ssh-add)
    fi
}

ensure_ssh_agent_started
ensure_ssh_key_added
exec $(non_bin_exec ssh) "$@"
