#! /usr/bin/env bash
set -e

usage()
{
cat << EOF
Usage: `basename $0` TAG [REMOTE=origin] [BRANCH=master]
EOF
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

TAG=$1
REMOTE=$2

if [ -z "$3" ]; then
    BRANCH=master
else
    BRANCH="$3"
fi

if [ -z "$2" ]; then
    REMOTE=origin
fi

git checkout $BRANCH
git pull --ff-only
git tag -u $GIT_AUTHOR_EMAIL -s -m "$TAG" $TAG
git push $REMOTE $BRANCH
git push $REMOTE $TAG
